# Generated by Django 3.2.16 on 2025-04-02 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='URL')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Watch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='URL')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Цена')),
                ('category_id', models.IntegerField(verbose_name='ID категории')),
                ('is_available', models.BooleanField(default=True, verbose_name='Доступность')),
                ('status', models.CharField(choices=[('AVAILABLE', 'Доступен'), ('OUT_OF_STOCK', 'Нет в наличии'), ('DISCONTINUED', 'Снят с продажи')], default='AVAILABLE', max_length=20, verbose_name='Статус')),
                ('image', models.CharField(blank=True, max_length=200, verbose_name='Изображение')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Часы',
                'verbose_name_plural': 'Часы',
                'ordering': ['-created_at'],
            },
        ),
    ]
