# Generated by Django 3.2.16 on 2025-04-15 17:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100, verbose_name='Название')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
            ],
            options={
                'verbose_name': 'Тег',
                'verbose_name_plural': 'Теги',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TechSpec',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mechanism', models.CharField(blank=True, max_length=100, verbose_name='Механизм')),
                ('water_resistance', models.CharField(blank=True, max_length=50, verbose_name='Водозащита')),
                ('case_material', models.CharField(blank=True, max_length=100, verbose_name='Материал корпуса')),
            ],
            options={
                'verbose_name': 'Технические характеристики',
                'verbose_name_plural': 'Технические характеристики',
            },
        ),
        migrations.AddField(
            model_name='watch',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='watches', to='WebApp.Tag', verbose_name='Теги'),
        ),
        migrations.AddField(
            model_name='watch',
            name='tech_spec',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='watch', to='WebApp.techspec', verbose_name='Технические характеристики'),
        ),
    ]
