# Generated by Django 5.2 on 2025-06-08 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='watch',
            options={'permissions': [('can_discount_watch', 'Может применять скидку на часы')]},
        ),
    ]
