# Generated by Django 3.2.16 on 2025-04-02 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0002_category_watch'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.RemoveField(
            model_name='watch',
            name='is_available',
        ),
    ]
